# TODO: add windows
name: ci

env:
  R2V: 5.9.0

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Installing radare2
      run: |
        wget "https://github.com/radareorg/radare2/releases/download/${R2V}/radare2_${R2V}_amd64.deb"
        wget "https://github.com/radareorg/radare2/releases/download/${R2V}/radare2-dev_${R2V}_amd64.deb"
        sudo dpkg -i "radare2_${R2V}_amd64.deb"
        sudo dpkg -i "radare2-dev_${R2V}_amd64.deb"
    - name: Setting up the Python virtual environment
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install pylint
    - name: Install Python dependencies
      run: |
        . venv/bin/activate
        pip install -r requirements.txt
    - name: Linting
      run: |
        . venv/bin/activate
        make cilint
    - name: Running r2ai from the shell
      run: |
        . venv/bin/activate
        python main.py -h
    - name: Running r2ai from r2
      run: |
        . venv/bin/activate
        r2 -q -i main.py -c r2ai /bin/ls
